Poll-master/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       # Load URLconf from polls.url module if the url starts with /polls
                       url(r'^polls/', include('polls.urls', namespace='polls')),

                       # Examples:
                       # url(r'^$', 'sites.views.home', name='home'),
                       # url(r'^sites/', include('sites.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
)

Poll-master/polls/urls.py
__author__ = 'shibly'

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^about/$', 'polls.views.about', name='about'),
                       url(r'^contact/$', 'polls.views.contact', name='contact'),
                       url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
                       url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
                       url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'))

Poll-master/polls/models.py
import datetime
from django.utils import timezone
from django.db import models
from django import forms
# Create your models here.


class Poll(models.Model):
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently ?'

    def __unicode__(self):
        return self.question

    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __unicode__(self):
        return self.choice_text

    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

Poll-master/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from polls.models import Choice, Poll, ContactForm
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """
        Returns the last five published polls
        """
        return Poll.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    # Tells django to use a specific template name instead of the auto generated default template name
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'


def about(request):
    return render(request, 'polls/about.html')


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
            recipient = ['shibly.phy@gmail.com']
            if cc_myself:
                recipient.append(sender)
            from django.core.mail import send_mail

            send_mail(subject, message, sender, recipient)
            return HttpResponseRedirect('/thanks/') # Redirect after post
    else:

        # Dynamic initial values.
        form = ContactForm(initial={'sender': 'shibly.phy@gmail.com'})
    return render(request, 'polls/contact.html', {'form': form})

Poll-master/polls/templates/polls/about.html
{% extends "polls/index.html" %}
{% block title %}About Poll App{% endblock %}
{% block body %}
    <div class="alert alert-info about">
        <h3 id="about">About poll app</h3>
    </div>
    <p>
        Online poll app is a django powered polling application influenced by Abu Ashraf Masnun's recent tutorial
        and official tutorial from Django's site. The app does a fairly simple job :). User will select a poll , choose
        an answer and vote it. An immediate result will be displayed just after the vote. The app uses django's builtin
        admin
        app and hook the poll app in it to provide an interface to perform CRUID operation on the app.

    </p>
{% endblock %}

Poll-master/polls/templates/polls/contact.html
{% extends "polls/index.html" %}
{% block title %}About Poll App{% endblock %}
{% block body %}
    <div class="alert alert-info about">
        <h3 id="about">Contact Us</h3>
    </div>
    <form action="/polls/contact/" method="post" class="form-vote"
          {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {% if form.subject.errors %}
                <div class="alert alert-error">
                    {{ form.subject.errors }}
                </div>
            {% endif %}
            <label for="id_subject">Email subject:</label>
            {{ form.subject }}
        </div>
        <div class="fieldWrapper">
            {% if form.message.errors %}
                <div class="alert alert-error">
                    {{ form.message.errors }}
                </div>
            {% endif %}
            <label for="id_message">Your message:</label>
            {{ form.message }}
        </div>
        <div class="fieldWrapper">
            {% if form.sender.errors %}
                <div class="alert alert-error">
                    {{ form.sender.errors }}
                </div>
            {% endif %}
            <label for="id_sender">Your email address:</label>
            {{ form.sender }}
        </div>
        <div class="fieldWrapper">
            {% if form.cc_myself.errors %}
                <div class="alert alert-error">
                    {{ form.cc_myself.errors }}
                </div>
            {% endif %}
            <label for="id_cc_myself">CC yourself?</label>
            {{ form.cc_myself }}
        </div>
        <input type="submit" class="btn btn-primary" value="Contact Us"/>
    </form>
{% endblock %}

Poll-master/polls/templates/polls/detail.html
{% extends "polls/index.html" %}
{% block title %}Poll Detail {% endblock %}
{% block body %}
    <div class="alert alert-success">
        <h2>{{ poll.question }}</h2>
    </div>
    {% if error_message %}
        <div class="alert alert-error">
            <p><strong>{{ error_message }}</strong></p>
        </div>
    {% endif %}
    <form class="form-vote" action="{% url 'polls:vote' poll.id %}" method="post">
        {% csrf_token %}
        {% for choice in poll.choice_set.all %}
            <input type="radio" class="radio inline control-label" name="choice" id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote" class="btn btn-primary"/>
    </form>

{% endblock %}

Poll-master/polls/templates/polls/details.html
<!DOCTYPE html>
<html>
<head>
    <title>Poll No Found</title>
</head>
<body>
{{ poll }}

</body>
</html>

Poll-master/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Latest Poll List{% endblock %}</title>
    {% block stylesheets %}
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap-responsive.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}"/>
        <script type="text/javascript" src="{% static 'polls/js/jquery-2.0.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>

<body>
<div class="container-narrow">
    <div class="masthead">

        <ul class="nav nav-pills pull-right">
            <li class="active"><a href="{% url 'polls:index' %}">Home</a></li>
            <li><a href="{% url 'polls:about' %}">About</a></li>
            <li><a href="{% url 'polls:contact' %}">Contact</a></li>
        </ul>
        <h3 class="muted">{% block header_title %}Poll App{% endblock %}</h3>
    </div>
    <hr>
    {% block body %}
        <table class="table table-striped table-bordered">
            <thead>
            <tr class="success">
                <th>Click on a poll bellow</th>
            </tr>
            </thead>
            <tbody>
            {% if latest_poll_list %}
                {% for poll in latest_poll_list %}
                    <tr>
                    <td>
                        <a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a>
                    </td>
                {% endfor %}
            {% else %}
                <td>Currently No polls are available.</td>
            {% endif %}
            </tr>
            </tbody>
        </table>
    {% endblock %}
    <div class="footer">
        <p>&copy; R O N Y 2015</p>
    </div>
</div>
</body>
</html>

Poll-master/polls/templates/polls/results.html
{% extends "polls/index.html" %}
{% block title %}Poll Result {% endblock %}

{% block body %}
    <div class="alert alert-success">
        <h2>{{ poll.question }}</h2>
    </div>
    <h3>Here is the result</h3>

    <ul>
        {% for choice in poll.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <ul>
        <li><a href="{% url 'polls:detail' poll.id %}">Vote again?</a></li>
        <li><a href="{% url 'polls:index' %}">Go back to Poll index</a></li>
    </ul>
{% endblock %}